### ISSUE TITLE
Design Homepage Mockup

### ISSUE THREAD

**Issue by tanvirchahal** [datopian/portal.js#30]
Moodboard: https://projects.invisionapp.com/boards/AG3ZZHGCD3F/

Acceptance Criteria
* [x] Mockup is designed in XD 
* [x] Mockup is reviewed by team for feedback
* [x] Feedback is implemented

Tasks
* [x] Brainstorm Ideas and create moodboard
* [x] Design v1 version of mockup (in-progress)
* [x] Get feedback 
* [x] Impelement feedback

## Final Version

link to XD: https://xd.adobe.com/view/14c00cb0-a290-41fd-a5d5-9b01ef758804-4193/

![fornow-dataportal](https://user-images.githubusercontent.com/56799741/87148883-e5e4c400-c2b7-11ea-822e-07d589f3309e.png)

**Comment by tanvirchahal** [comment]
Mockup v1 - https://xd.adobe.com/view/71d2c65c-a105-4b12-9285-6a1ca882afab-2481/

**Comment by monikappv** [comment]
here are a few hero section mockup suggestions..

1.
<img width="470" alt="1_2" src="https://user-images.githubusercontent.com/56799741/86654451-a33c9680-bfee-11ea-81fa-0788ac8d2357.PNG">
2. 
<img width="461" alt="2_2" src="https://user-images.githubusercontent.com/56799741/86654459-a3d52d00-bfee-11ea-92a1-f1af22ce582a.PNG">
3. 
<img width="475" alt="3_2" src="https://user-images.githubusercontent.com/56799741/86654464-a46dc380-bfee-11ea-8b73-115246b8718d.PNG">
4.
<img width="473" alt="4" src="https://user-images.githubusercontent.com/56799741/86654469-a5065a00-bfee-11ea-9790-d4a10d3fff18.PNG">
5. 
<img width="456" alt="5" src="https://user-images.githubusercontent.com/56799741/86654472-a59ef080-bfee-11ea-9242-903288322d13.PNG">
6. 
<img width="484" alt="6" src="https://user-images.githubusercontent.com/56799741/86654473-a6378700-bfee-11ea-8ead-1fbf83180069.PNG">
7. 
<img width="459" alt="7" src="https://user-images.githubusercontent.com/56799741/86654476-a6d01d80-bfee-11ea-8735-11a1f271529e.PNG">
8.
<img width="479" alt="8" src="https://user-images.githubusercontent.com/56799741/86654483-a768b400-bfee-11ea-9012-fcc9171ae258.PNG">
9. 
<img width="477" alt="9" src="https://user-images.githubusercontent.com/56799741/86654485-a8014a80-bfee-11ea-95e6-5abf7ccf0b59.PNG">
10. 
<img width="479" alt="10" src="https://user-images.githubusercontent.com/56799741/86654487-a899e100-bfee-11ea-9ce2-fd39a518d59c.PNG">
11.
<img width="477" alt="11" src="https://user-images.githubusercontent.com/56799741/86654494-a9327780-bfee-11ea-814b-d624106228b3.PNG">
12. 
<img width="493" alt="12" src="https://user-images.githubusercontent.com/56799741/86654496-a9cb0e00-bfee-11ea-8a14-858bca30d19c.PNG">
13.
<img width="480" alt="13" src="https://user-images.githubusercontent.com/56799741/86654498-aa63a480-bfee-11ea-87e4-fe04ffc5613d.PNG">

**Comment by monikappv** [comment]
@rufuspollock forgot to tag you here... see my comment above

**Comment by rufuspollock** [comment]
@monikappv great start. maybe a few fewer options (esp where similar) as a bit overwhelming.  4 or 5 are my preference but too small to compare fonts atm (just looking at layouts).

**Comment by anuveyatsu** [comment]
@monikappv @rufuspollock 5 and 11 for me. Generally, I prefer making it simple (no complex CSS / JS).

**Comment by rufuspollock** [comment]
@monikappv and to be clear on 4 i think the grey would be good and you could probably do a straight line (though curve is nicer).

@anuveyatsu we do want this to be pretty "swish" - a bit of a wow, that's striking / nice.

**Comment by monikappv** [comment]
@rufuspollock @anuveyatsu 

here's an XD link containing the 5 best out of the 13 hero section suggestions.
https://xd.adobe.com/view/501f6386-a1cd-4d84-a9c9-81f9a08a73cc-054c/

these are number 4, 5 and 11 that you guys liked + 2 other that I picked.

I also straightened the line of number 4 as @rufuspollock suggested.

**Comment by monikappv** [comment]
@rufuspollock 
here are 3 options for the hero section the way we discussed it yesterday (with the coloured set of balloons and background etc..) 
https://xd.adobe.com/view/dd8dd7ab-fd72-48c9-9624-6eb9bdbd7d2c-88de/

to be honest, I liked the version with the transparent balloons with outlines more, these are a bit too much I think. 
but do let me know what you think..

**Comment by rufuspollock** [comment]
@monikappv could you confirm what were the few changes we'd proposed (e.g. copy and paste image with the notes) and confirm that is done. In general in terms of layout i like the first option i think.

**Comment by monikappv** [comment]
@rufuspollock I shared the xd file with the last 3 versions with you (sent you an invite few hours ago)

this was the version that we picked out of the suggested ones

<img width="365" alt="option4" src="https://user-images.githubusercontent.com/56799741/87719349-e4396580-c7bb-11ea-9bb1-840f4279528c.PNG">

here is @rufuspollock's comment on it
```
Let's go for option 4 with background colouring of option 5 and the set of balloons from the original
```

so the end result is

![fornow-dataportal](https://user-images.githubusercontent.com/56799741/87148883-e5e4c400-c2b7-11ea-822e-07d589f3309e.png)

* added background as in no.4
* coloured the balloons

**Comment by rufuspollock** [comment]
@monikappv nice - i think it is good to go. Can you link the xd file in the description to implementors have access and then close this as FIXED.

**Comment by monikappv** [comment]
FIXED.

See `Final version` section in the issue description.
