### ISSUE TITLE
Converting CKAN descriptor to Data Package spec

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal.js#31]
In the frontend-v2, we've been creating converter functions for doing this. Since we're using Apollo in frontend-v3, we could utilize its apollo-link-rest provided functions to convert CKAN descriptor into data packages: `fieldNameNormalizer`, `bodySerializers`, `responseTransformer`. Read more here https://www.apollographql.com/docs/link/links/rest/#options

@rufuspollock wdyt?

**Comment by rufuspollock** [comment]
WONTFIX. Since we are deprioritizing Catalog i don't think we will do this for now.
