### ISSUE TITLE
[epic] v0.3 of new frontend portal app

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal.js#34]
## Acceptance criteria

- [ ] I can register/login to frontend app
- [ ] ...
- [ ] Permissions ?

**Comment by steveoni** [comment]
Pull request #53 add this feature to Portal.js. Auth0 is used for authentication, users can log in and logout. The user state is also available globally, hence it can be used for permission for some pages.

**Comment by anuveyatsu** [comment]
@steveoni I've left a comment in that PR #53  
Could you please check it?

cc @rufuspollock

**Comment by rufuspollock** [comment]
INVALID. This was never very fully described and catalog stuff is not priority atm so closing as INVALID. (NB: We actually have done login already in a portal-based app so could say that part is done).
