### ISSUE TITLE
Fix Jest Tests

### ISSUE THREAD

**Issue by abhishekgahlot** [datopian/portal.js#39]
All the jest tests are broken. We need to fix it.

Current Tests:

 - [x] __tests__/pages/index.test.tsx
 - [x]  __tests__/components/search/Total.test.tsx
 - [x]  __tests__/components/search/List.test.tsx
 - [x]  __tests__/components/search/Item.test.tsx
 - [x]  __tests__/components/search/Form.test.tsx

**Comment by abhishekgahlot** [comment]
The WordPress API to use is v2 and here are the formats.

Posts: `${URL}/wp-json/wp/v2/posts`
Posts Slug: `${URL}/wp/v2/posts?slug=tweet-from-usdatagov-1654`

**Comment by rufuspollock** [comment]
FIXED. @abhishekgahlot says this is all done - see https://github.com/datopian/portal.js/commit/0c80f8479419fc79b6d8d44e125b614d36c84148
