### ISSUE TITLE
Investigate/Fix the CI

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/portal.js#55]
Investigate and fix the CI as it's failing for some time already.

**Comment by anuveyatsu** [comment]
@steveoni could you start with formatting this issue's description per our standard here: https://playbook.datopian.com/issues-tasks/#creating-issues

**Comment by steveoni** [comment]
Whenever a new change is made and push to GitHub, the CI kept failing

## Acceptance

- [ ] Analyze why the CI is failing

**Comment by steveoni** [comment]
Note: I was not able to inspect `Vercel` deploymentation error

**Comment by rufuspollock** [comment]
@steveoni the vercel deployment error is probably because it is vercel account of someone else. We could just disable the vercel build for now (separate issue).
